support for SoaringPilot added

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11422,7 +11422,7 @@ echo "${ECHO_T}$install_it" >&6
   fi
 done
 
-ac_config_files="$ac_config_files ./Makefile doc/Makefile doc/en/Makefile kflog/Makefile kflog/guicontrols/Makefile kflog/kfrfil/Makefile kflog/kfrgcs/Makefile kflog/kfrgmn/Makefile kflog/map-icons/Makefile kflog/map-icons/small/Makefile kflog/pics/Makefile po/Makefile"
+ac_config_files="$ac_config_files ./Makefile doc/Makefile doc/en/Makefile kflog/Makefile kflog/guicontrols/Makefile kflog/kfrfil/Makefile kflog/kfrgcs/Makefile kflog/kfrgmn/Makefile kflog/kfrxsp/Makefile kflog/map-icons/Makefile kflog/map-icons/small/Makefile kflog/pics/Makefile po/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -11750,13 +11750,14 @@ do
   "kflog/kfrfil/Makefile" ) CONFIG_FILES="$CONFIG_FILES kflog/kfrfil/Makefile" ;;
   "kflog/kfrgcs/Makefile" ) CONFIG_FILES="$CONFIG_FILES kflog/kfrgcs/Makefile" ;;
   "kflog/kfrgmn/Makefile" ) CONFIG_FILES="$CONFIG_FILES kflog/kfrgmn/Makefile" ;;
+  "kflog/kfrxsp/Makefile" ) CONFIG_FILES="$CONFIG_FILES kflog/kfrxsp/Makefile" ;;
   "kflog/map-icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES kflog/map-icons/Makefile" ;;
   "kflog/map-icons/small/Makefile" ) CONFIG_FILES="$CONFIG_FILES kflog/map-icons/small/Makefile" ;;
   "kflog/pics/Makefile" ) CONFIG_FILES="$CONFIG_FILES kflog/pics/Makefile" ;;
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:11759: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:11760: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12107,7 +12108,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12110: creating $ac_file" >&5
+    { echo "$as_me:12111: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12125,7 +12126,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12128: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12129: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12138,7 +12139,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12141: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12142: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12199,7 +12200,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:12202: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:12203: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -12210,7 +12211,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12213: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12214: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12223,7 +12224,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12226: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12227: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12340,7 +12341,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:12343: $ac_file is unchanged" >&5
+      { echo "$as_me:12344: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
